<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BasisPengetahuan extends Seeder
{
    public function run()
    {
        $data = [
           //PET/PETE
        [ 'jenis_kemasan_id' => 1, 'kriteria_produk_id' => 1,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       [ 'jenis_kemasan_id' => 1, 'kriteria_produk_id' => 2,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       [ 'jenis_kemasan_id' => 1, 'kriteria_produk_id' => 3,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       [ 'jenis_kemasan_id' => 1, 'kriteria_produk_id' => 4,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       [ 'jenis_kemasan_id' => 1, 'kriteria_produk_id' => 5,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       [ 'jenis_kemasan_id' => 1, 'kriteria_produk_id' => 7,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       [ 'jenis_kemasan_id' => 1, 'kriteria_produk_id' => 9,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       [ 'jenis_kemasan_id' => 1, 'kriteria_produk_id' => 10,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       [ 'jenis_kemasan_id' => 1, 'kriteria_produk_id' => 11,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 1, 'kriteria_produk_id' => 13,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 1, 'kriteria_produk_id' => 14,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 1, 'kriteria_produk_id' => 15,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 1, 'kriteria_produk_id' => 16,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 1, 'kriteria_produk_id' => 18,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 1, 'kriteria_produk_id' => 19,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],

       //HDPE
       [ 'jenis_kemasan_id' => 2, 'kriteria_produk_id' => 1,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 2,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 4,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ], 
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 5,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 7,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 8,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 9,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 10,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 12,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 13,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 14,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 15,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 16,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 17,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 18,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 19,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 2, 'kriteria_produk_id' => 20,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],

       //PVC
       [ 'jenis_kemasan_id' => 3, 'kriteria_produk_id' => 1,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 2,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 3,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],   
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 4,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 5,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 7,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 9,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 10,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 12,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 14,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 15,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 16,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 18,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 3, 'kriteria_produk_id' => 19,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       
       //LDPE
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 1,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 2,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],   
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 3,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],   
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 4,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 5,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 7,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 9,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 10,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 12,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 13,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 14,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 15,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 16,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 17,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 18,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 4, 'kriteria_produk_id' => 19,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],

       //PP
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 2,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],   
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 3,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],   
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 4,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],   
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 5,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 7,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 10,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 13,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 14,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 15,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 16,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 17,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 18,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 19,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 5, 'kriteria_produk_id' => 20,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],

       //NYLON
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 1,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 2,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],  
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 3,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 6,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 7,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 8,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ], 
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 9,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 10,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 14,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 15,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 16,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 17,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 18,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 19,   'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
       ['jenis_kemasan_id' => 6, 'kriteria_produk_id' => 20,  'created_date' => date("Y-m-d H:i:s"),
           'updated_date' => date("Y-m-d H:i:s") ],
    ];
    
        // Using Query Builder
        $this->db->table('basis_pengetahuan')->insertBatch($data);
    }
}
